### ISSUE TITLE
Error using camera in trail.py

### ISSUE THREAD

**Issue by ahinoamp** [marcomusy/vtkplotter-examples#2]
Hi,

Thanks for the wonderful software. 
While running the example trail.py, I get the following error:

`vp.camera.Zoom(1.2)
AttributeError: 'NoneType' object has no attribute 'Zoom'`

Do you have any idea what could be the problem?

Thank you,

Noe

**Comment by marcomusy** [comment]
Hi thanks a lot for your interest and for spotting a possible problem.
Are you by chance running the script in a jupyter notebook?
If so, it's a limitation of the notebook environment, unfortunately there is no easy way to implement animations in notebooks.
You can still pop a normal rendering window from the notebook with:
```python 
from vtkplotter import settings
settings.embedWindow(False)
# ...
```

**Comment by ahinoamp** [comment]
Perfect! I got the script to work by using the rendering window.

**Comment by marcomusy** [comment]
Dear Noe,
in the latest release there is the possibility to draw static images in the notebook with option:
`embedWindow('2d')`
M.
