### ISSUE TITLE
Installation on a RaspberryPi 4

### ISSUE THREAD

**Issue by Rbravo555** [marcomusy/vtkplotter-examples#4]
Good day,

I am trying to install vtkplotter on a raspberry pi 4 with 4GB RAM with ubuntu 19.10 64 bits, and I get the following error when attempting to install using "pip3 install -U vtkplotter":

> Could not find a version that satisfies the requirement vtk (from vtkplotter) (from versions: )

>No matching distribution found for vtk (from vtkplotter)

Any advises on how to install it?

**Comment by marcomusy** [comment]
Hi,
I have no experience with raspberry.. I could only find this:
https://blog.kitware.com/raspberry-pi-likes-vtk/

so you need to compile manually..and i'm not sure if the information is still up to date with later versions of vtk.
vtkplotter needs vtk >=7 and uses matplotlib's colormaps.

**Comment by Rbravo555** [comment]
Thanks for the reply

It does seem that the information you mention is up to date. I should then be able to compile vtk, and once I have it, it should be possible to run vtkplotter, right? I'll give it a try. 

Actually I think I posted this issue in the wrong repository, it should have been posted in the main one...

**Comment by marcomusy** [comment]
> Thanks for the reply
> 
> It does seem that the information you mention is up to date. I should then be able to compile vtk, and once I have it, it should be possible to run vtkplotter, right?

Yes! Compile it with python wrapping set on.

> Actually I think I posted this issue in the wrong repository, it should have been posted in the main one...

no worries!

**Comment by Rbravo555** [comment]
> > Thanks for the reply
> > It does seem that the information you mention is up to date. I should then be able to compile vtk, and once I have it, it should be possible to run vtkplotter, right?
> 
> Yes! Compile it with python wrapping set on.

I just got you there. I had to compile VTK with python wrapper set to ON. I was looking how to set python wrapper on in vtkplotter...

**Comment by marcomusy** [comment]
no, you don't need to set anything in vtkplotter.. only in vtk (in the cmake options I guess).

**Comment by Rbravo555** [comment]
After compiling VTK7.1.1 following https://blog.kitware.com/raspberry-pi-likes-vtk/ and setting PYTHON_WRAP=ON, it is possible to run VTKPLOTTER on the RaspberryPi 4.

Thanks

![Screenshot from 2020-01-30 11-16-40](https://user-images.githubusercontent.com/46027276/73445271-37c10f80-4352-11ea-882a-ba6cf3f080d9.png)

**Comment by marcomusy** [comment]
Fantastic! Thanks for your feedback!
M.
